apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netcat
  template:
    metadata:
      labels:
        app: netcat
    spec:
      containers:
        - name: netcat
          image: nicolaka/netshoot
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo -e "HTTP/1.1 200 OK\r\nContent-Length: 38\r\n\r\nHello, this is a response from netcat!\r\n" | nc -l -p 80 -q 1;
              done
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
