apiVersion: v1
kind: Service
metadata:
  name: netcat-external
spec:
  type: NodePort
  selector:
    app: netcat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#      nodePort: 31000   # 外部からアクセスするポート（省略可能、Kubernetes が自動割当）
